### ISSUE TITLE
Trying to install the PIT and accompanying Apex application on autonomous cloud.

### ISSUE THREAD

**Issue by ANDREAS-MARKUS** [j-sieben/PIT#20]
Good afternoon,

Trying to install the PIT and accompanying Apex application on autonomous cloud. 

The install script for PIT mentions:
`-- PIT_MAIL may be installed after installing UTL_TEXT`
`--@modules/pit_mail/install.sql`
But when I install PIT first and UTL_TEXT next and then PIT with uncommented @modules/pit_mail/install.sql, I lose the UTL_TEXT messages and I end up with an invalid UTL_TEXT. I'm a bit in a chicken-egg sitiuation...

I have to disable this set plsql_code_type - is it really neccesary?
-- insufficient privileges for this one on autonomous cloud
-- alter session set plsql_code_type='NATIVE';

Also using PIT_OWNER schema name as password is not allowed, I have to include a separate parameter with password.

There is no tablespace user on cloud, the default permanent tablespace is data. Maybe fetching the default permanent tablespace and using that, is more robust?

**Comment by j-sieben** [comment]
Hi Andreas,

thank you for pointing me on these issues. 

In regard to installing PIT_MAIL, I was unclear in the script and added a more meaningful comment there. What I wanted to say is:
You may install PIT_MAIL after having installed UTL_TEXT by calling the installation script PIT_INSTALL_MODULE. Please provide the install user, the default language and the name of the module to install.

The second issue you have found is easy to solve: Compiling a central tool like PIT natively is a small boost in performance but you can securely omit this setting. The code will run independently, the only difference is that by setting this parameter, the PL/SQL portions of PIT are compiled into native C-Code, enhancing performance for the PL/SQL part of the code, not the SQL part.

I understand that using the owner name  as password is forbidden due to password complexity policies. I need to create a parameter for the users I create. I maybe change that behavior and use the username reversely, but this may cause other problems such as minimum length and the like. hm… Maybe it's more secure to provide a random password and print it out upon installation.

I will definitely change my scripts and omit the tablespace USERS in advance of a default tablespace. I think your advice is valuable here, let me add this to the script.

Best regards,

Jürgen


Am 20.08.2021 um 16:01 schrieb Andreas Markus Groenevelt ***@***.***>:

**Comment by j-sieben** [comment]
Hi Andreas,

keep in mind though that output module PIT_MAIL is somewhat specific to the environment I was in when creating this package. I added support for several authentication methods and they may work as expected, but if you have other possibilities to connect a mail server and send mails, you may want to adopt this output module to your needs. After all, the PIT_MAIL_PKG is a simple PL/SQL package that is triggered by PIT and provided with a message object, but what you want to do with the mail is very much up to you.

Best regards,

Jürgen

**Comment by ANDREAS-MARKUS** [comment]
Hello there!
I think you should remove the new_password variable in pit_install.sql at row 22?

`@tools/check_users_exist.sql &INSTALL_USER. &NEW_PASSWORD.`

**Comment by ANDREAS-MARKUS** [comment]
Another one: when I run pit_install.sql second time, it crashes on check_users_exist.sql. I guess the predicate on row 12 should not refer to user but to username instead:
`where user = upper('&1.');`

**Comment by ANDREAS-MARKUS** [comment]
The pit_uninstall.sql always stumbles over the non-existing PIT_TEST module... what is it for? Or should it only be present for you as developer of PIT?

**Comment by ANDREAS-MARKUS** [comment]
Pardon all my questioning, but why is the @modules/pit_table/install_client.sql run twice in the pit_install_client.sql? It seems to be doing exactly the same things...

**Comment by j-sieben** [comment]
Hi Andreas,

sorry for answering so late to your questions, I was off for some days.
You’re right with every point you made and I corrected them. Thank you for pointing me to these issues. The reason for all this is simple, I was mistaken by copy errors etc.

One word to the PIT_TEST module: If utplsql is installed, the install script will also install the TEST functionality. I have to admit that the tests are somewhat out of sync, I would need to look trough them. Initial idea besides automatic unit testing was to have something available that checks for proper installation, but the requirement for that is not really there anymore. So maybe I will decide to remove the unit test suite and only keep a local copy here.
The PIT_TEST module is used within the automatic unit tests. It needs to report the outcome of the tests to something. I can*t rely on a module like PIT_TABLE, as this will not necessarily react on all ‚event‘ types. Therefore, the PIT_TEST module reports the output of PIT to the unit tests. I corrected the path to the deinstallation file so it won’t moan about this anymore. I installed and uninstalled it on a fresh database user and it does give me any errors, but it’s hard for me to test every installation option such as installing with a different FLAG_TYPE setting, against an non existing or existing user etc. But I hope it will run more stable now.

Best regards,

Jürgen

**Comment by ANDREAS-MARKUS** [comment]
The password generated, gets rejected quite often, because it doesn't contain (enough) numbers or special characters. That's because their relative shares differ in the pool. Changing line 22 in check_users_exist.sql to this helps (not perfect):
`substr('ABZDEFGHIJKLMNOPQRSTUVWXYZabzdefghijklmnopqrstuvwxyz012345678901234567890123456789#_@#_@#_@#_@#_@#_@#_@#_@', trunc(position), 1), '') within group (order by idx) pwd`

Same goes for UTL_TEXT

**Comment by j-sieben** [comment]
Hi Andreas,

thanks again for pointing me to this. I now created the (hopefullly) ultimate solution by integrating a separate create password function. You can control the length, amount of number and amount of special chars. I parameterized it so that a password of 12 char length with 3 numbers and 3 special chars is created. Chars are mixed case. This now adheres to the requirements of the oracle strong password verification policy but it can be easily adopted to your requirements by changing the parameters. At least it should now avoid errors when running the script.

Best regards,

Jürgen

**Comment by ANDREAS-MARKUS** [comment]
Hello Jürgen,

I am trying to install the new install set on Oracle Cloud and I noticed these two points in check_context_prerequisites.sql:
Suppose I have created the context PIT_CTX_PIT_OWNER and granted select on DBA_CONTEXT (maybe READ could suffice?). In that case PIT_OWNER has no need for the CREATE ANY CONTEXT privilege. But you're checking for the context in ALL_OBJECTS, but as all contexts are owned by SYS and PIT_OWNER has no grants on DBA_OBJECTS either, it will never pass that test. I think you should query DBA_CONTEXT instead, as you requested an explicit grant on it for PIT_OWNER.
But even if it did pass, the code will always check for the CREATE ANY CONTEXT privilege and then fail to install  the CONTEXT framework.

**Comment by j-sieben** [comment]
Hi Andreas,

fighting with the various possibilities in regard to the context has taken me into the wilderness, I think.

Her are the scenarios I can think of:

1. In any case, DBA_CONTEXT has to be reachable, so I check this first.
2. It could be that the context already exists. In that case, I install the context framework, but I don’t need the CREATE ANY CONTEXT then
3. If the context does not yet exist, I need to have the CREATE_ANY_CONTEXT grant.

If none of the above mentioned prerequisites are true, I will not install the framework but fallback to the SESSION_ADAPTER approach. Having access to DBA_CONTEXT is not sufficient to install the framework, either 2 or 3 have to be true as well.

I tried my best to make the checks clearer. Hopefully they work now. It’s hard to test all different scenarios…

Best regards,

Jürgen

**Comment by ANDREAS-MARKUS** [comment]
Good evening Jürgen,

Well that was fast! But I almost don't dare to say; I still have a thingy... Maybe it's specific to the cloud environment. I don't know. I don't have a stand-alone Oracle instance available with dba-access. But on the OCDB, as ADMIN user (no access to SYS on OCDB), when I create the PIT_OWNER user and grant READ or SELECT to DBA_CONTEXT and grant CREATE ANY CONTEXT to PIT_OWNER and then switch to PIT_OWNER and then do
```
create or replace context pit_ctx_pit_owner using pit_owner.utl_context accessed globally
/
```
It then shows up via
`select * from DBA_CONTEXT where namespace = 'PIT_CTX_PIT_OWNER';`

But not from
`select * from ALL_objects where object_type = 'CONTEXT' and object_name = 'PIT_CTX_PIT_OWNER';`

Even more so, not any object_type = 'CONTEXT' yields any results in PIT_OWNER and DBA_OBJECTS is not available to PIT_OWNER.

If I switch back to ADMIN, then querying the DBA_OBJECTS does find the context, but querying the ALL_OBJECTS also doesn't find any CONTEXT object type.

That's why I would suggest to check for the existence of the PIT_CTX_PIT_OWNER context via dba_context, instead of via all_objects. So, instead of:

```
select count(*)
    into l_is_installed
    from all_objects
   where object_type = 'CONTEXT'
     and object_name = 'PIT_CTX_' || user; 
```
to do this:

```
select count(*)
    into l_is_installed
    from dba_context
where namespace =  'PIT_CTX_' || user; 

```

**Comment by j-sieben** [comment]
Hi Andreas,

never mind, I’m really glad you look into this so thoroughly and let me know about your findings. I wanted to avoid querying against DBA_CONTEXT because if you don’t have a grant on it, the code even won’t compile. I now query using dynamic SQL and that seems to do the trick. I hope, it now works fine on the cloud service as well.

Best regards, 
Jürgen
