### ISSUE TITLE
Issue with pit_install_client.sql

### ISSUE THREAD

**Issue by Stefan-Pz** [j-sieben/PIT#8]
Hi Jürgen,
sorry, it's me again with a hopefully small issue ;-) After the sucessful installation I wanted to grant access to my test user to start building a demo.
A hint: During installation I set the boolean parameter as follows:
`define FLAG_TYPE="number(1, 0)";
define C_TRUE=1;
define C_FALSE=0;`

Thanks a lot for any help!

output of pit_install_client.sql

`INSTALL_USER                   REMOTE_USER
------------------------------ ------------------------------
PIT_OWNER                      POS8FE

ORA_NAME_TYPE                  ORA_MAX_LENGTH
------------------------------ --------------
varchar2(128 byte)                 ##########

********************************************************************************
*** Installing PIT client POS8FE

********************************************************************************
*** Checking whether required users exist
**  Checking owner user PIT_OWNER
.    - User PIT_OWNER exists.
**  Check whether PIT_OWNER has privilege create session
.    - System privilege create session is already granted.

**  Grant access to PARAM installation

**  Granting access to parameter package to POS8FE
*   Clean up schema POS8FE
.    -  revoking client rights
*   Grant access rights to POS8FE
.    - Granting execute on param to POS8FE
.    - Create synonym param for PIT_OWNER.param at POS8FE
.    - Granting execute on param_admin to POS8FE
.    - Create synonym param_admin for PIT_OWNER.param_admin at POS8FE
.    - Granting select, references on parameter_group to POS8FE
.    - Create synonym parameter_group for PIT_OWNER.parameter_group at POS8FE
.    - Granting select, references on parameter_realm to POS8FE
.    - Create synonym parameter_realm for PIT_OWNER.parameter_realm at POS8FE
.    - Granting select, references on parameter_tab to POS8FE
.    - Create synonym parameter_tab for PIT_OWNER.parameter_tab at POS8FE
.    - Granting select, references on parameter_type to POS8FE
.    - Create synonym parameter_type for PIT_OWNER.parameter_type at POS8FE
.    - Granting select on parameter_core_vw to POS8FE
.    - Create synonym parameter_core_vw for PIT_OWNER.parameter_core_vw at POS8FE
.    - Granting select on parameter_realm_vw to POS8FE
.    - Create synonym parameter_realm_vw for PIT_OWNER.parameter_realm_vw at POS8FE
*   Change current schema to POS8FE
*   Create PIT user tables and views
.    - Create table PARAMETER_LOCAL
.    - Create view PARAMETER_VW
       coalesce(pal_boolean_value, par_boolean_value) par_boolean_value,
                                   *
FEHLER in Zeile 10:
ORA-00932: Inkonsistente Datentypen: CHAR erwartet, NUMBER erhalten`

**Comment by j-sieben** [comment]
Hi Stefan,

thank you for pointing me to these issues. I must admit that I didn’t change the settings for quite some time now, so obviously some errors made it into the scripts.

The problem was different this time though: There is a separat init file INIT_CLIENT.sql where you normally would have to adjust the FLAG_TYPE as well. I agree that this is too error prone, therefore I added a new file called SETTINGS.SQL at folder INIT. There you can set your settings centrally, this file will be referenced by the other installation files and adjust the flag type accordingly.

Hopefully, anything will work now. If you don’t want to go through the whole process of installing PIT again, you may adjust the settings in the beforementioned file. Client installation should work then. I checked the enhancement in.

Thank you again for coming back to me on this.

Best regards

ConDeS GmbH & Co. KG
Jürgen Sieben

Mühlenstraße 229
41236 Mönchengladbach

Phone: +49-2166-12 44 33

**Comment by Stefan-Pz** [comment]
Good morning Jürgen, thanks for providing for your quick solution, I'm glad I can contribute a little bit.
